/**
 * Language Context - AfroPlan
 * Système de traduction multi-langues
 * Langues supportées: FR, EN, DE, ES
 */

import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

// Types
export type Language = 'fr' | 'en' | 'de' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string) => string;
  languages: { code: Language; name: string; flag: string }[];
}

// Available languages
const LANGUAGES = [
  { code: 'fr' as Language, name: 'Français', flag: '🇫🇷' },
  { code: 'en' as Language, name: 'English', flag: '🇬🇧' },
  { code: 'de' as Language, name: 'Deutsch', flag: '🇩🇪' },
  { code: 'es' as Language, name: 'Español', flag: '🇪🇸' },
];

// Translations
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.close': 'Fermer',
    'common.next': 'Suivant',
    'common.back': 'Retour',
    'common.search': 'Rechercher',
    'common.attention': 'Attention',
    'common.seeAll': 'Voir tout',
    'common.seeResults': 'Voir les résultats',
    'common.results': 'résultats',
    'common.noResults': 'Aucun résultat trouvé',
    'common.refresh': 'Actualiser',
    'common.refreshResults': 'Actualisation des résultats...',
    'common.distance': 'Distance',
    'common.rating': 'Note',
    'common.price': 'Prix',
    'common.errorOccurred': 'Une erreur est survenue. Veuillez réessayer.',
    'common.administration': 'Administration',
    'common.backofficeAccess': 'Accès Backoffice',
    'common.backofficeSubtitle': 'Gérer les utilisateurs, salons et revenus',
    'common.testerFeedback': 'Retours Testeurs',
    'common.testerFeedbackSubtitle': 'Voir les bugs et suggestions',
    'common.settings': 'Paramètres',
    'common.support': 'Support & Légal',
    'common.help': 'Aide & Contact',
    'common.privacy': 'Confidentialité',
    'common.language': 'Langue',

    // Checkout
    'checkout.title': 'Paiement',
    'checkout.secure': 'Paiement sécurisé',
    'checkout.yourBooking': 'Votre réservation',
    'checkout.choosePaymentType': 'Choisir le type de paiement',
    'checkout.depositOnly': 'Payer un acompte',
    'checkout.fullPayment': 'Paiement total',
    'checkout.paymentMethod': 'Mode de paiement',
    'checkout.creditCard': 'Carte bancaire',
    'checkout.priceDetail': 'Détail du prix',
    'checkout.servicePrice': 'Prix de la prestation',
    'checkout.depositNow': 'Acompte à payer maintenant',
    'checkout.payFull': 'Payer le total',
    'checkout.payDeposit': 'Payer l\'acompte',
    'checkout.remainingAtSalon': 'Reste à payer au salon',
    'checkout.termsNotice': 'En confirmant, vous acceptez les conditions d\'annulation et de remboursement d\'AfroPlan.',
    'checkout.paymentSuccess': 'Paiement réussi !',
    'checkout.paymentSuccessDesc': 'Votre rendez-vous est maintenant confirmé.',
    'checkout.paymentError': 'Échec du paiement',
    'checkout.paymentErrorDesc': 'Une erreur est survenue lors de la transaction.',
    'checkout.viewBooking': 'Voir mon RDV',
    'checkout.idMissing': 'ID de réservation manquant',
    'checkout.welcomeMsg': 'Bonjour ! Ma réservation pour le {date} à {time} est confirmée.',
    'checkout.cancelNoticeTitle': 'Politique d\'annulation',
    'checkout.cancelNoticeDesc': 'Annulation gratuite jusqu\'à 48h avant le RDV. Passé ce délai, aucun remboursement ne sera effectué.',

    // Auth
    'auth.login': 'Connexion',
    'auth.register': 'Inscription',
    'auth.logout': 'Déconnexion',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.forgotPassword': 'Mot de passe oublié ?',
    'auth.noAccount': 'Pas de compte ?',
    'auth.hasAccount': 'Déjà un compte ?',
    'auth.loginRequired': 'Connexion requise',
    'auth.loginRequiredMessage': 'Vous devez être connecté pour effectuer cette action.',
    'auth.profile': 'Mon Profil',
    'auth.loginToManage': 'Connectez-vous pour gérer vos réservations et votre profil.',
    'auth.editProfile': 'Modifier mon profil',
    'auth.nameRequired': 'Le nom est obligatoire.',
    'auth.profileUpdated': 'Profil mis à jour avec succès.',
    'auth.updateError': 'Impossible de mettre à jour le profil.',
    'auth.cameraPermission': 'Permission d\'accès à la galerie refusée.',
    'auth.fullName': 'Nom complet',
    'auth.phone': 'Téléphone',
    'auth.logoutConfirm': 'Voulez-vous vous déconnecter ?',

    // Role
    'role.switchToCoiffeur': 'Espace Coiffeur',
    'role.manageYourSalon': 'Gérer votre salon et vos réservations',
    'role.switchToClient': 'Espace Client',

    // Home
    'home.welcome': 'Bienvenue sur AfroPlan',
    'home.hello': 'Bonjour',
    'home.readyForHairstyle': 'Disponible pour une nouvelle coiffure ?',
    'home.featured': 'À la une',
    'home.hairstyleCategories': 'Catégories de coiffures',
    'home.seeLess': 'Voir moins',
    'home.searchSalon': 'Rechercher mon salon / coiffeur',
    'home.searchSubtitle': 'Trouve le style qui te correspond',
    'home.promotions': 'Offres du moment',
    'home.hairstyles': 'Styles de coiffure',
    'home.nearbyCoiffeurs': 'Coiffeurs à proximité',
    'home.popularSalons': 'Salons populaires',
    'home.tipsAndInspiration': 'Conseils & Inspiration',
    'home.areYouCoiffeur': 'Tu es coiffeur(se) ?',
    'home.joinAfroPlanPro': 'Rejoins AfroPlan Pro et développe ton activité',
    'home.discoverPro': 'Découvrir AfroPlan Pro',

    // Onboarding
    'onboarding.slide1Title': 'Révélez votre style',
    'onboarding.slide1Subtitle': 'Découvrez les meilleurs coiffeurs afro de votre région.',
    'onboarding.slide2Title': 'Réservation simple',
    'onboarding.slide2Subtitle': 'Prenez rendez-vous en quelques clics, à tout moment.',
    'onboarding.slide3Title': 'Expertise certifiée',
    'onboarding.slide3Subtitle': 'Des professionnels passionnés pour prendre soin de vous.',
    'onboarding.touchToContinue': 'Touchez l\'écran pour continuer',

    // Role Selection
    'role.tagline': 'La beauté afro à portée de main',
    'role.chooseSpace': 'Choisissez votre univers',
    'role.clientSpace': 'Espace Client',
    'role.clientSubtitle': 'Je souhaite découvrir des salons et réserver une prestation.',
    'role.coiffeurSpace': 'Espace Coiffeur',
    'role.coiffeurSubtitle': 'Je souhaite gérer mon salon et recevoir des réservations.',
    'role.trust': 'Plus de 500 salons nous font confiance',

    // Search Flow
    'search.findCoiffeur': 'Trouve facilement ton coiffeur afro',
    'search.quickQuestions': 'Quelques questions rapides pour te proposer les meilleurs salons.',
    'search.chooseStyle': 'Choisis ta coiffure',
    'search.chooseCategory': 'Choisis ta catégorie',
    'search.whatTypeHairstyle': 'Quel type de coiffure cherches-tu ?',
    'search.step': 'Étape',
    'search.of': 'sur',
    'search.backAtAnyTime': 'Tu peux revenir en arrière à tout moment',
    'search.locationTemporarilyDisabled': 'Localisation désactivée (temporairement)',
    'search.whatStyle': 'Quel style te ferait plaisir ?',
    'search.quickFilter': 'Filtre rapide',
    'search.optional': 'Optionnel - Affine ta recherche',
    'search.hairType': 'Type de cheveux',
    'search.whereCoiffeur': 'Où souhaites-tu te faire coiffer ?',
    'search.inSalon': 'En salon',
    'search.atHome': 'À domicile',
    'search.goToSalon': 'Se déplacer au salon',
    'search.coiffeurComesHome': 'Le coiffeur vient chez vous',
    'search.budgetDistance': 'Budget & Distance',
    'search.maxBudget': 'Budget maximum',
    'search.maxDistance': 'Distance maximum',
    'search.showAllSalons': 'Je veux voir tous les salons (ignorer les filtres)',
    'search.paymentInfo': 'Tu pourras choisir de payer le montant total ou un acompte lors de la réservation.',
    'search.canGoBack': 'Tu peux revenir en arrière à tout moment',
    'search.quickPay': 'Paiement rapide',

    // Reservations
    'booking.myReservations': 'Mes réservations',
    'booking.book': 'Réserver',
    'booking.confirmed': 'Confirmé',
    'booking.pending': 'En attente',
    'booking.cancelled': 'Annulé',
    'booking.completed': 'Terminé',
    'booking.loginMessage': 'Connectez-vous pour voir vos rendez-vous',
    'booking.noUpcoming': 'Aucun rendez-vous à venir',
    'booking.noPast': 'Aucun rendez-vous passé',
    'booking.exploreSalons': 'Explorer les salons',
    'booking.discoverSalonsMessage': 'Découvrez nos salons et prenez rendez-vous !',
    'booking.cancelImpossible': 'Annulation impossible',
    'booking.cancelImpossibleMessage': 'Ce rendez-vous a été validé par un acompte. Veuillez contacter directement le salon.',
    'booking.cancelAndRefund': 'Annuler et rembourser ?',
    'booking.cancelPenaltyMessage': 'Une pénalité de 20% s\'applique pour toute annulation payée d\'avance.',
    'booking.amountPaid': 'Montant payé',
    'booking.cancelFee': 'Frais d\'annulation',
    'booking.amountRefunded': 'Montant remboursé',
    'booking.keepAppt': 'Conserver mon RDV',
    'booking.confirmCancel': 'Confirmer l\'annulation',
    'booking.cancelSuccess': 'Votre rendez-vous a été annulé.',
    'booking.cancelRefundProcessing': 'Votre remboursement est en cours.',
    'booking.cancelAppt': 'Annuler le rendez-vous',
    'booking.cancelConfirmMessage': 'Voulez-vous vraiment annuler ce rendez-vous ?',
    'booking.cancelFinalSuccess': 'Votre rendez-vous a été définitivement supprimé.',
    'booking.deleteError': 'Impossible de supprimer le rendez-vous.',
    'booking.noEdit': 'Ce rendez-vous ne peut plus être modifié.',
    'booking.cancelReason': 'Motif d\'annulation',
    'booking.unavailable': 'Indisponible',
    'booking.noPhone': 'Aucun numéro de téléphone.',
    'booking.incompleteAddress': 'L\'adresse est incomplète.',
    'booking.upcoming': 'À venir',
    'booking.past': 'Passés',
    'booking.yes': 'Oui',
    'booking.no': 'Non',
    'booking.yesCancel': 'Oui, annuler',
    'booking.wantToContinue': 'Voulez-vous continuer ?',

    // Chat
    'chat.writeMessage': 'Écrivez votre message...',
    'chat.online': 'En ligne',
    'chat.reservationConfirmed': 'Réservation confirmée ! Vous pouvez discuter.',
    'chat.willBeLate': "J'aurai un peu de retard",
    'chat.onMyWay': 'Je suis en route',
    'chat.whatTime': 'À quelle heure exactement ?',
    'chat.sendAddress': "Pouvez-vous m'envoyer l'adresse ?",

    // Coiffeur Dashboard
    'coiffeur.dashboard': 'Tableau de bord',
    'coiffeur.weeklyRevenue': 'Revenus de la semaine',
    'coiffeur.weeklyAppt': 'RDV/sem.',
    'coiffeur.today': 'Aujourd\'hui',
    'coiffeur.rating': 'Note',
    'coiffeur.activity': 'Activité',
    'coiffeur.estimatedNet': 'Revenus (Net estimé)',
    'coiffeur.total': 'Total',
    'coiffeur.fees': 'Frais',
    'coiffeur.net': 'Net',
    'coiffeur.proActions': 'Actions professionnelles',
    'coiffeur.flashBoost': 'Boost Flash',
    'coiffeur.manualAppt': 'RDV Manuel',
    'coiffeur.manualApptTitle': 'Nouveau RDV Manuel',
    'coiffeur.manualApptDesc': 'Enregistrez un rendez-vous pris hors application.',
    'coiffeur.clientName': 'Nom du client',
    'coiffeur.service': 'Prestation',
    'coiffeur.yourServices': 'VOS PRESTATIONS',
    'coiffeur.date': 'Date',
    'coiffeur.time': 'Heure',
    'coiffeur.saveAppt': 'Enregistrer le rendez-vous',
    'coiffeur.flashBoostTitle': 'Boost de dernière minute 🚀',
    'coiffeur.flashBoostDesc': 'Activer une promotion flash de -15% pendant 4 heures ?',
    'coiffeur.later': 'Plus tard',
    'coiffeur.activateBoost': 'Activer le Boost',
    'coiffeur.boostActivated': 'Boost activé !',
    'coiffeur.boostActivatedDesc': 'Votre promotion est en ligne.',
    'coiffeur.clientMode': 'Mode Client',
    'coiffeur.bookService': 'Réserver une prestation',
    'coiffeur.readyToLaunch': 'Prêt à lancer votre salon ?',
    'coiffeur.setupShowcase': 'Configurez votre vitrine pour recevoir des clients.',
    'coiffeur.createSalon': 'Créer mon salon',
    'coiffeur.restrictedAccess': 'Accès restreint',
    'coiffeur.init': 'Initialisation...',
    'coiffeur.all': 'Toutes',
    'coiffeur.pending': 'En attente',
    'coiffeur.confirmed': 'Confirmées',
    'coiffeur.blockDay': 'Bloquer ma journée (Urgence)',
    'coiffeur.unblockDay': 'Débloquer ma journée',
    'coiffeur.noReservations': 'Aucune réservation',
    'coiffeur.reservationsAppear': 'Les réservations apparaîtront ici',
    'coiffeur.paymentMethod': 'Mode de paiement',
    'coiffeur.paidOnline': 'Payé en ligne',
    'coiffeur.remainingAtSalon': 'Reste à payer au salon',
    'coiffeur.confirm': 'Confirmer',
    'coiffeur.cancel': 'Annuler',
    'coiffeur.message': 'Message',
    'coiffeur.validated': 'Rendez-vous validé',
    'coiffeur.confirmTitle': 'Confirmer la réservation',
    'coiffeur.confirmDesc': 'Voulez-vous confirmer cette réservation ?',
    'coiffeur.confirmSuccess': 'Le rendez-vous a été confirmé.',
    'coiffeur.cancelTitle': 'Annuler le rendez-vous',
    'coiffeur.cancelWarning': 'Attention : Votre réponse impacte votre image.',
    'coiffeur.cancelReasonLabel': 'Raison de l\'annulation :',
    'coiffeur.cancelReasonPlaceholder': 'Ex: Urgence personnelle...',
    'coiffeur.keepAppt': 'Conserver le rendez-vous',
    'coiffeur.confirmCancel': 'Confirmer l\'annulation',
    'coiffeur.refundNote': '* Le client sera remboursé automatiquement.',
    'coiffeur.blockDayConfirm': 'Fermer toutes vos réservations pour aujourd\'hui ?',
    'coiffeur.unblockDayConfirm': 'Rouvrir vos réservations pour aujourd\'hui ?',
    'coiffeur.blockSuccess': 'Votre journée a été bloquée.',
    'coiffeur.unblockSuccess': 'Vos réservations sont à nouveau ouvertes !',
    'coiffeur.cancelSuccess': 'Le rendez-vous a été annulé.',
    'coiffeur.scheduleUpdated': 'Horaires mis à jour.',
    'coiffeur.scheduleUpdateError': 'Impossible d\'enregistrer les horaires.',
    'coiffeur.confirmError': 'Impossible de confirmer.',
    'coiffeur.cancelError': 'Impossible d\'annuler.',
    'coiffeur.dayAlreadyBlocked': 'Journée déjà bloquée.',
    'coiffeur.blockDayUrgency': 'Urgences : Bloquer ma journée',
    'coiffeur.yesBlock': 'Oui, bloquer',
    'coiffeur.yesUnblock': 'Oui, débloquer',
    'coiffeur.unblockDayTitle': 'Débloquer ma journée',
    'coiffeur.myStyles': 'Mes styles',
    'coiffeur.catalog': 'Catalogue',
    'coiffeur.myPrestations': 'Mes prestations',
    'coiffeur.loadingPrestations': 'Chargement...',
    'coiffeur.catalogHint': 'Cochez les styles que vous proposez.',
    'coiffeur.alreadyConfigured': 'Configuré',
    'coiffeur.addOtherPrestations': 'Ajouter d\'autres prestations',
    'coiffeur.noPrestation': 'Aucune prestation',
    'coiffeur.viewCatalog': 'Voir le catalogue',
    'coiffeur.removeStyle': 'Retirer ce style',
    'coiffeur.publishSalonNow': 'PUBLIER MON SALON',
    'coiffeur.salonOnline': 'SALON EN LIGNE',
    'coiffeur.unpublish': 'Dépublier',
    'coiffeur.configStyles': 'Configurer les styles',
    'coiffeur.configStyle': 'Configurer le style',
    'coiffeur.configTitle': 'Configuration',
    'coiffeur.priceEuro': 'Prix (€)',
    'coiffeur.durationMin': 'Durée (min)',
    'coiffeur.saveSuccess': 'Sauvegardé avec succès.',
    'coiffeur.publishTitle': 'Publier votre salon',
    'coiffeur.publishDesc': 'Votre salon sera visible par tous.',
    'coiffeur.publishCongrat': 'Félicitations ! 🎉',
    'coiffeur.publishCongratDesc': 'Votre salon est en ligne.',
    'coiffeur.managePrices': 'Gérer mes tarifs',
    'coiffeur.rdvManagement': 'Gestion des RDV',
    'coiffeur.manageReservations': 'Gérez facilement vos réservations',
    'coiffeur.moreClients': 'Plus de clients',
    'coiffeur.increaseVisibility': 'Augmentez votre visibilité',
    'coiffeur.statistics': 'Statistiques',
    'coiffeur.trackPerformance': 'Suivez vos performances',
    'coiffeur.payments': 'Paiements',
    'coiffeur.securePayment': 'Encaissez en toute sécurité',
    'coiffeur.readyToStart': 'Prêt à commencer ?',
    'coiffeur.createProAccount': 'Créer mon compte Pro',
    'coiffeur.needPhotoHelp': 'Besoin d\'aide pour vos photos ?',
    'coiffeur.photoHelpDesc': 'Contactez-nous pour de l\'aide gratuite !',

    // Favorites
    'fav.favorites': 'Favoris',
    'fav.favoritesSubtitle': 'Vos salons et styles préférés',
    'fav.yourFavorites': 'Vos favoris',
    'fav.loginMessage': 'Connectez-vous pour sauvegarder vos favoris.',
    'fav.salons': 'Salons',
    'fav.styles': 'Styles',
    'fav.noFavorites': 'Aucun favori pour le moment',
    'fav.noStylesSaved': 'Aucun style sauvegardé pour le moment',
    'fav.removeSuccess': 'Retiré des favoris',

    // Profile
    'profile.settings': 'Paramètres',
    'profile.language': 'Langue',
    'profile.notifications': 'Notifications',
    'profile.help': 'Aide',
    'profile.about': 'À propos',
    'profile.rdv': 'RDV',
    'profile.salons': 'Salons',
    'profile.spent': 'Dépensé',
    'profile.modeCoiffeur': 'Mode Coiffeur',
    'profile.switchToCoiffeur': 'Espace coiffeur',
    'profile.recentBookings': 'Rendez-vous récents',
    'profile.seeAll': 'Tout voir',
    'profile.noRecentBookings': 'Aucun rendez-vous récent',
    'profile.messagesAlerts': 'Messages & Alertes',
    'profile.myConversations': 'Mes conversations',
    'profile.myConversationsDesc': 'Échanges avec vos coiffeurs',
    'profile.notificationsDesc': 'Historique des alertes',
    'profile.account': 'Compte',
    'profile.editProfile': 'Modifier le profil',
    'profile.editProfileDesc': 'Nom, photo, informations',
    'profile.settingsDesc': 'Langue, sécurité',
    'profile.helpSupport': 'Aide & Support',
    'profile.logout': 'Se déconnecter',
    'profile.editProfileTitle': 'Modifier mon profil',
    'profile.fullName': 'Nom complet',
    'profile.phone': 'Téléphone',
    'profile.saveChanges': 'Enregistrer les modifications',
    'profile.appLanguage': 'Langue de l\'application',
    'profile.preferences': 'Préférences',
    'profile.pushNotifications': 'Notifications Push',
    'profile.darkMode': 'Mode Sombre automatique',
    'profile.user': 'Utilisateur',
    'profile.logoutConfirm': 'Voulez-vous vous déconnecter ?',

    // Hairstyles
    'hairstyle.tresses': 'Tresses',
    'hairstyle.locks': 'Locks',
    'hairstyle.coupe': 'Coupe',
    'hairstyle.soins': 'Soins',
    'hairstyle.coloration': 'Coloration',
    'hairstyle.tissage': 'Tissage',
    'hairstyle.cornrows': 'Cornrows',
    'hairstyle.afro': 'Afro',

    // Salon Detail
    'salon.about': 'À propos',
    'salon.services': 'Services',
    'salon.reviews': 'Avis',
    'salon.address': 'Adresse',
    'salon.bookNow': 'Réserver maintenant',
    'salon.openingHours': 'Horaires d\'ouverture',
    'salon.contact': 'Contact',
    'salon.noServices': 'Aucun service disponible.',
    'salon.noReviews': 'Aucun avis.',
    'salon.verified': 'Vérifié',
    'salon.call': 'Appeler',
    'salon.share': 'Partager',
    'salon.directions': 'Itinéraire',
    'salon.gallery': 'Galerie',
    'salon.stylists': 'Coiffeurs',
    'salon.selectService': 'Choisissez vos services',
    'salon.selectedServices': 'services sélectionnés',
    'salon.totalPrice': 'Total',
    'salon.book': 'Continuer',

    // Salon Registration
    'salon.photos': 'Photos du salon',
    'salon.addPhotos': 'Ajoutez vos photos',
    'salon.info': 'Informations du salon',
    'salon.name': 'Nom du salon',
    'salon.description': 'Description',
    'salon.phone': 'Téléphone',
    'salon.email': 'Email',
    'salon.location': 'Localisation',
    'salon.address': 'Adresse',
    'salon.city': 'Ville',
    'salon.postalCode': 'Code postal',
    'salon.specialties': 'Spécialités',
    'salon.save': 'Enregistrer',
    'salon.saving': 'Enregistrement...',
    'salon.saved': 'Salon enregistré !',
    'salon.homeService': 'Service à domicile',
    'salon.homeServiceFee': 'Frais de déplacement',
  },

  en: {
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.next': 'Next',
    'common.back': 'Back',
    'common.search': 'Search',
    'common.attention': 'Attention',
    'common.seeAll': 'See all',
    'common.seeResults': 'See results',
    'common.results': 'results',
    'common.noResults': 'No results found',
    'common.refresh': 'Refresh',
    'common.refreshResults': 'Refreshing results...',
    'common.distance': 'Distance',
    'common.rating': 'Rating',
    'common.price': 'Price',
    'common.errorOccurred': 'An error occurred. Please try again.',

    // Auth
    'auth.login': 'Login',
    'auth.register': 'Sign up',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': 'No account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.loginRequired': 'Login required',
    'auth.loginRequiredMessage': 'You must be logged in to perform this action.',

    // Home
    'home.welcome': 'Welcome to AfroPlan',
    'home.hello': 'Hello',
    'home.readyForHairstyle': 'Ready for a new hairstyle?',
    'home.featured': 'Featured',
    'home.hairstyleCategories': 'Hairstyle Categories',
    'home.seeLess': 'See less',
    'home.searchSalon': 'Search salon / stylist',
    'home.searchSubtitle': 'Find your perfect style',
    'home.promotions': 'Current offers',
    'home.hairstyles': 'Hairstyles',
    'home.nearbyCoiffeurs': 'Nearby stylists',
    'home.popularSalons': 'Popular salons',
    'home.tipsAndInspiration': 'Tips & Inspiration',
    'home.areYouCoiffeur': 'Are you a stylist?',
    'home.joinAfroPlanPro': 'Join AfroPlan Pro and grow your business',
    'home.discoverPro': 'Discover AfroPlan Pro',

    // Onboarding
    'onboarding.slide1Title': 'Reveal your style',
    'onboarding.slide1Subtitle': 'Discover the best afro stylists in your area.',
    'onboarding.slide2Title': 'Easy booking',
    'onboarding.slide2Subtitle': 'Book an appointment in a few clicks, anytime.',
    'onboarding.slide3Title': 'Certified expertise',
    'onboarding.slide3Subtitle': 'Passionate professionals to take care of you.',
    'onboarding.touchToContinue': 'Touch the screen to continue',

    // Search Flow
    'search.findCoiffeur': 'Find your afro stylist easily',
    'search.quickQuestions': 'A few quick questions to suggest the best salons.',
    'search.chooseStyle': 'Choose your hairstyle',
    'search.chooseCategory': 'Choose your category',
    'search.whatTypeHairstyle': 'What type of hairstyle?',
    'search.step': 'Step',
    'search.of': 'of',
    'search.backAtAnyTime': 'You can go back at any time',
    'search.locationTemporarilyDisabled': 'Location temporarily disabled',
    'search.whatStyle': 'What style would you like?',
    'search.quickFilter': 'Quick filter',
    'search.hairType': 'Hair type',
    'search.whereCoiffeur': 'Where would you like to be styled?',
    'search.inSalon': 'In salon',
    'search.atHome': 'At home',
    'search.budgetDistance': 'Budget & Distance',
    'search.maxBudget': 'Max budget',
    'search.maxDistance': 'Max distance',
    'search.showAllSalons': 'Show all salons (ignore filters)',
    'search.paymentInfo': 'Choose full or deposit payment at booking.',
    'search.quickPay': 'Quick pay',

    // Booking
    'booking.myReservations': 'My bookings',
    'booking.book': 'Book',
    'booking.confirmed': 'Confirmed',
    'booking.pending': 'Pending',
    'booking.cancelled': 'Cancelled',
    'booking.completed': 'Completed',
    'booking.loginMessage': 'Login to see your bookings',
    'booking.noUpcoming': 'No upcoming appointments',
    'booking.noPast': 'No past appointments',
    'booking.exploreSalons': 'Explore salons',
    'booking.cancelImpossible': 'Cannot cancel',
    'booking.cancelAndRefund': 'Cancel and refund?',
    'booking.amountPaid': 'Amount paid',
    'booking.cancelFee': 'Cancel fee',
    'booking.amountRefunded': 'Amount refunded',
    'booking.keepAppt': 'Keep appointment',
    'booking.confirmCancel': 'Confirm cancellation',
    'booking.cancelSuccess': 'Appointment cancelled.',
    'booking.cancelRefundProcessing': 'Refund in progress.',
    'booking.cancelAppt': 'Cancel appointment',
    'booking.cancelConfirmMessage': 'Are you sure you want to cancel?',
    'booking.cancelFinalSuccess': 'Appointment deleted.',
    'booking.deleteError': 'Could not delete appointment.',
    'booking.noEdit': 'Cannot edit anymore.',
    'booking.cancelReason': 'Cancel reason',
    'booking.unavailable': 'Unavailable',
    'booking.upcoming': 'Upcoming',
    'booking.past': 'Past',
    'booking.yes': 'Yes',
    'booking.no': 'No',
    'booking.yesCancel': 'Yes, cancel',
    'booking.wantToContinue': 'Do you want to continue?',

    // Chat
    'chat.writeMessage': 'Write a message...',
    'chat.online': 'Online',
    'chat.reservationConfirmed': 'Booking confirmed! Start chatting.',
    'chat.willBeLate': "I'll be a bit late",
    'chat.onMyWay': "I'm on my way",
    'chat.whatTime': 'What time exactly?',
    'chat.sendAddress': 'Can you send the address?',

    // Coiffeur Dashboard
    'coiffeur.dashboard': 'Dashboard',
    'coiffeur.weeklyRevenue': 'Weekly revenue',
    'coiffeur.weeklyAppt': 'Appt/week',
    'coiffeur.today': 'Today',
    'coiffeur.rating': 'Rating',
    'coiffeur.activity': 'Activity',
    'coiffeur.estimatedNet': 'Revenue (Estimated Net)',
    'coiffeur.total': 'Total',
    'coiffeur.fees': 'Fees',
    'coiffeur.net': 'Net',
    'coiffeur.proActions': 'Pro actions',
    'coiffeur.flashBoost': 'Flash Boost',
    'coiffeur.manualAppt': 'Manual Appt',
    'coiffeur.manualApptTitle': 'New Manual Appt',
    'coiffeur.manualApptDesc': 'Record an appointment taken outside the app.',
    'coiffeur.clientName': 'Client name',
    'coiffeur.service': 'Service',
    'coiffeur.yourServices': 'YOUR SERVICES',
    'coiffeur.date': 'Date',
    'coiffeur.time': 'Time',
    'coiffeur.saveAppt': 'Save appointment',
    'coiffeur.flashBoostTitle': 'Flash Boost 🚀',
    'coiffeur.flashBoostDesc': 'Activate -15% off for the next 4 hours?',
    'coiffeur.later': 'Later',
    'coiffeur.activateBoost': 'Activate Boost',
    'coiffeur.boostActivated': 'Boost activated!',
    'coiffeur.boostActivatedDesc': 'Promotion is live.',
    'coiffeur.clientMode': 'Client Mode',
    'coiffeur.bookService': 'Book a service',
    'coiffeur.readyToLaunch': 'Ready to launch your salon?',
    'coiffeur.setupShowcase': 'Setup your showcase to receive clients.',
    'coiffeur.createSalon': 'Create my salon',
    'coiffeur.restrictedAccess': 'Restricted access',
    'coiffeur.init': 'Initializing...',
    'coiffeur.all': 'All',
    'coiffeur.pending': 'Pending',
    'coiffeur.confirmed': 'Confirmed',
    'coiffeur.blockDay': 'Block day (Emergency)',
    'coiffeur.unblockDay': 'Unblock day',
    'coiffeur.noReservations': 'No bookings',
    'coiffeur.reservationsAppear': 'Bookings will appear here',
    'coiffeur.paymentMethod': 'Payment method',
    'coiffeur.paidOnline': 'Paid online',
    'coiffeur.remainingAtSalon': 'Remaining at salon',
    'coiffeur.confirm': 'Confirm',
    'coiffeur.cancel': 'Cancel',
    'coiffeur.message': 'Message',
    'coiffeur.validated': 'Booking validated',
    'coiffeur.confirmTitle': 'Confirm booking',
    'coiffeur.confirmDesc': 'Confirm this booking?',
    'coiffeur.confirmSuccess': 'Booking confirmed.',
    'coiffeur.cancelTitle': 'Cancel booking',
    'coiffeur.cancelWarning': 'Caution: Your response impacts your image.',
    'coiffeur.cancelReasonLabel': 'Cancel reason:',
    'coiffeur.cancelReasonPlaceholder': 'Ex: Emergency...',
    'coiffeur.keepAppt': 'Keep appointment',
    'coiffeur.confirmCancel': 'Confirm cancellation',
    'coiffeur.refundNote': '* Client will be refunded automatically.',
    'coiffeur.blockDayConfirm': 'Close all bookings for today?',
    'coiffeur.unblockDayConfirm': 'Reopen bookings for today?',
    'coiffeur.blockSuccess': 'Day blocked.',
    'coiffeur.unblockSuccess': 'Bookings reopened!',
    'coiffeur.cancelSuccess': 'Booking cancelled.',
    'coiffeur.scheduleUpdated': 'Hours updated.',
    'coiffeur.scheduleUpdateError': 'Could not save hours.',
    'coiffeur.confirmError': 'Could not confirm.',
    'coiffeur.cancelError': 'Could not cancel.',
    'coiffeur.dayAlreadyBlocked': 'Day already blocked.',
    'coiffeur.blockDayUrgency': 'Emergency: Block my day',
    'coiffeur.yesBlock': 'Yes, block',
    'coiffeur.yesUnblock': 'Yes, unblock',
    'coiffeur.unblockDayTitle': 'Unblock my day',
    'coiffeur.myStyles': 'My styles',
    'coiffeur.catalog': 'Catalog',
    'coiffeur.myPrestations': 'My services',
    'coiffeur.loadingPrestations': 'Loading...',
    'coiffeur.catalogHint': 'Check styles you offer.',
    'coiffeur.alreadyConfigured': 'Configured',
    'coiffeur.addOtherPrestations': 'Add other services',
    'coiffeur.noPrestation': 'No service',
    'coiffeur.viewCatalog': 'View catalog',
    'coiffeur.removeStyle': 'Remove style',
    'coiffeur.publishSalonNow': 'PUBLISH MY SALON',
    'coiffeur.salonOnline': 'SALON ONLINE',
    'coiffeur.unpublish': 'Unpublish',
    'coiffeur.configStyles': 'Configure styles',
    'coiffeur.configStyle': 'Configure style',
    'coiffeur.configTitle': 'Configuration',
    'coiffeur.priceEuro': 'Price (€)',
    'coiffeur.durationMin': 'Duration (min)',
    'coiffeur.saveSuccess': 'Successfully saved.',
    'coiffeur.publishTitle': 'Publish your salon',
    'coiffeur.publishDesc': 'Visible to everyone.',
    'coiffeur.publishCongrat': 'Congrats! 🎉',
    'coiffeur.publishCongratDesc': 'Salon is online.',
    'coiffeur.managePrices': 'Manage rates',
    'coiffeur.rdvManagement': 'Appt Management',
    'coiffeur.manageReservations': 'Manage bookings easily',
    'coiffeur.moreClients': 'More clients',
    'coiffeur.increaseVisibility': 'Increase visibility',
    'coiffeur.statistics': 'Statistics',
    'coiffeur.trackPerformance': 'Track performance',
    'coiffeur.payments': 'Payments',
    'coiffeur.securePayment': 'Collect payments securely',
    'coiffeur.readyToStart': 'Ready to start?',
    'coiffeur.createProAccount': 'Create Pro account',
    'coiffeur.needPhotoHelp': 'Need photo help?',
    'coiffeur.photoHelpDesc': 'Contact us for free help!',

    // Favorites
    'fav.favorites': 'Favorites',
    'fav.favoritesSubtitle': 'Your favorite salons and styles',
    'fav.yourFavorites': 'Your favorites',
    'fav.loginMessage': 'Login to save your favorites.',
    'fav.salons': 'Salons',
    'fav.styles': 'Styles',
    'fav.noFavorites': 'No favorites yet',
    'fav.noStylesSaved': 'No styles saved yet',
    'fav.removeSuccess': 'Removed from favorites',

    // Profile
    'profile.settings': 'Settings',
    'profile.language': 'Language',
    'profile.notifications': 'Notifications',
    'profile.help': 'Help',
    'profile.about': 'About',
    'profile.rdv': 'Appt',
    'profile.salons': 'Salons',
    'profile.spent': 'Spent',
    'profile.modeCoiffeur': 'Stylist Mode',
    'profile.switchToCoiffeur': 'Stylist space',
    'profile.recentBookings': 'Recent appointments',
    'profile.seeAll': 'See all',
    'profile.noRecentBookings': 'No recent appointments',
    'profile.messagesAlerts': 'Messages & Alerts',
    'profile.myConversations': 'My conversations',
    'profile.myConversationsDesc': 'Chats with your stylists',
    'profile.notificationsDesc': 'Alerts history',
    'profile.account': 'Account',
    'profile.editProfile': 'Edit profile',
    'profile.editProfileDesc': 'Name, photo, information',
    'profile.settingsDesc': 'Language, security',
    'profile.helpSupport': 'Help & Support',
    'profile.logout': 'Logout',
    'profile.editProfileTitle': 'Edit my profile',
    'profile.fullName': 'Full name',
    'profile.phone': 'Phone',
    'profile.saveChanges': 'Save changes',
    'profile.appLanguage': 'App language',
    'profile.preferences': 'Preferences',
    'profile.pushNotifications': 'Push Notifications',
    'profile.darkMode': 'Automatic Dark Mode',
    'profile.user': 'User',
    'profile.logoutConfirm': 'Want to logout?',

    // Hairstyles
    'hairstyle.tresses': 'Braids',
    'hairstyle.locks': 'Locks',
    'hairstyle.coupe': 'Cut',
    'hairstyle.soins': 'Care',
    'hairstyle.coloration': 'Coloring',
    'hairstyle.tissage': 'Weave',
    'hairstyle.cornrows': 'Cornrows',
    'hairstyle.afro': 'Afro',

    // Salon Detail
    'salon.about': 'About',
    'salon.services': 'Services',
    'salon.reviews': 'Reviews',
    'salon.address': 'Address',
    'salon.bookNow': 'Book now',
    'salon.openingHours': 'Opening hours',
    'salon.contact': 'Contact',
    'salon.noServices': 'No services available.',
    'salon.noReviews': 'No reviews.',
    'salon.verified': 'Verified',
    'salon.call': 'Call',
    'salon.share': 'Share',
    'salon.directions': 'Directions',
    'salon.gallery': 'Gallery',
    'salon.stylists': 'Stylists',
    'salon.selectService': 'Select services',
    'salon.selectedServices': 'services selected',
    'salon.totalPrice': 'Total',
    'salon.book': 'Continue',

    // Salon Registration
    'salon.photos': 'Salon photos',
    'salon.addPhotos': 'Add your photos',
    'salon.info': 'Salon information',
    'salon.name': 'Salon name',
    'salon.description': 'Description',
    'salon.phone': 'Phone',
    'salon.email': 'Email',
    'salon.location': 'Location',
    'salon.address': 'Address',
    'salon.city': 'City',
    'salon.postalCode': 'Postal code',
    'salon.specialties': 'Specialties',
    'salon.save': 'Save',
    'salon.saving': 'Saving...',
    'salon.saved': 'Salon saved!',
    'salon.homeService': 'Home service',
    'salon.homeServiceFee': 'Travel fee',
  },

  de: {
    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.cancel': 'Abbrechen',
    'common.confirm': 'Bestätigen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.close': 'Schließen',
    'common.next': 'Weiter',
    'common.back': 'Zurück',
    'common.search': 'Suchen',
    'common.attention': 'Achtung',
    'common.seeAll': 'Alle ansehen',
    'common.seeResults': 'Ergebnisse ansehen',
    'common.results': 'Ergebnisse',
    'common.noResults': 'Keine Ergebnisse gefunden',
    'common.refresh': 'Aktualisieren',
    'common.refreshResults': 'Aktualisierung...',
    'common.distance': 'Entfernung',
    'common.rating': 'Bewertung',
    'common.price': 'Preis',
    'common.errorOccurred': 'Fehler aufgetreten.',

    // Auth
    'auth.login': 'Anmelden',
    'auth.register': 'Registrieren',
    'auth.logout': 'Abmelden',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.noAccount': 'Kein Konto?',
    'auth.hasAccount': 'Schon ein Konto?',
    'auth.loginRequired': 'Anmeldung erforderlich',
    'auth.loginRequiredMessage': 'Bitte melden Sie sich an.',

    // Home
    'home.welcome': 'Willkommen bei AfroPlan',
    'home.hello': 'Hallo',
    'home.readyForHairstyle': 'Bereit für eine neue Frisur?',
    'home.featured': 'Empfohlen',
    'home.hairstyleCategories': 'Frisuren-Kategorien',
    'home.seeLess': 'Weniger anzeigen',
    'home.searchSalon': 'Salon / Friseur suchen',
    'home.searchSubtitle': 'Finde deinen perfekten Stil',
    'home.promotions': 'Aktuelle Angebote',
    'home.hairstyles': 'Frisuren',
    'home.nearbyCoiffeurs': 'Friseure in der Nähe',
    'home.popularSalons': 'Beliebte Salons',
    'home.tipsAndInspiration': 'Tipps & Inspiration',
    'home.areYouCoiffeur': 'Bist du Friseur?',
    'home.joinAfroPlanPro': 'Wachse mit AfroPlan Pro',
    'home.discoverPro': 'AfroPlan Pro entdecken',

    // Onboarding
    'onboarding.slide1Title': 'Enthülle deinen Stil',
    'onboarding.slide1Subtitle': 'Entdecke die besten Afro-Friseure in deiner Nähe.',
    'onboarding.slide2Title': 'Einfache Reservierung',
    'onboarding.slide2Subtitle': 'Buche einen Termin mit wenigen Klicks, jederzeit.',
    'onboarding.slide3Title': 'Zertifizierte Expertise',
    'onboarding.slide3Subtitle': 'Leidenschaftliche Profis kümmern sich um dich.',
    'onboarding.touchToContinue': 'Tippe auf den Bildschirm, um fortzufahren',

    // Search Flow
    'search.findCoiffeur': 'Afro-Friseur einfach finden',
    'search.quickQuestions': 'Ein paar Fragen für die besten Salons.',
    'search.chooseStyle': 'Wähle deine Frisur',
    'search.chooseCategory': 'Wähle deine Kategorie',
    'search.whatTypeHairstyle': 'Welche Frisur?',
    'search.step': 'Schritt',
    'search.of': 'von',
    'search.backAtAnyTime': 'Du kannst jederzeit zurück',
    'search.locationTemporarilyDisabled': 'Standort deaktiviert',
    'search.whatStyle': 'Welchen Stil möchtest du?',
    'search.quickFilter': 'Schnellfilter',
    'search.hairType': 'Haartyp',
    'search.whereCoiffeur': 'Wo frisieren lassen?',
    'search.inSalon': 'Im Salon',
    'search.atHome': 'Zu Hause',
    'search.budgetDistance': 'Budget & Entfernung',
    'search.maxBudget': 'Max Budget',
    'search.maxDistance': 'Max Entfernung',
    'search.showAllSalons': 'Alle Salons anzeigen',
    'search.paymentInfo': 'Voll- oder Anzahlung wählbar.',
    'search.quickPay': 'Schnellzahlung',

    // Booking
    'booking.myReservations': 'Meine Buchungen',
    'booking.book': 'Buchen',
    'booking.confirmed': 'Bestätigt',
    'booking.pending': 'Ausstehend',
    'booking.cancelled': 'Storniert',
    'booking.completed': 'Abgeschlossen',
    'booking.loginMessage': 'Anmelden für Buchungen',
    'booking.noUpcoming': 'Keine anstehenden Termine',
    'booking.noPast': 'Keine vergangenen Termine',
    'booking.exploreSalons': 'Salons erkunden',
    'booking.cancelImpossible': 'Storno unmöglich',
    'booking.cancelAndRefund': 'Stornieren & Erstatten?',
    'booking.amountPaid': 'Bezahlt',
    'booking.cancelFee': 'Stornogebühr',
    'booking.amountRefunded': 'Erstattet',
    'booking.keepAppt': 'Termin behalten',
    'booking.confirmCancel': 'Storno bestätigen',
    'booking.cancelSuccess': 'Termin storniert.',
    'booking.cancelRefundProcessing': 'Erstattung läuft.',
    'booking.cancelAppt': 'Termin absagen',
    'booking.cancelConfirmMessage': 'Sicher stornieren?',
    'booking.cancelFinalSuccess': 'Termin gelöscht.',
    'booking.deleteError': 'Löschen fehlgeschlagen.',
    'booking.noEdit': 'Nicht mehr änderbar.',
    'booking.cancelReason': 'Stornogrund',
    'booking.unavailable': 'Nicht verfügbar',
    'booking.upcoming': 'Bevorstehend',
    'booking.past': 'Vergangen',
    'booking.yes': 'Ja',
    'booking.no': 'Nein',
    'booking.yesCancel': 'Ja, stornieren',
    'booking.wantToContinue': 'Möchten Sie fortfahren?',

    // Chat
    'chat.writeMessage': 'Nachricht schreiben...',
    'chat.online': 'Online',
    'chat.reservationConfirmed': 'Buchung bestätigt! Chatten.',
    'chat.willBeLate': 'Ich komme etwas später',
    'chat.onMyWay': 'Ich bin unterwegs',
    'chat.whatTime': 'Wann genau?',
    'chat.sendAddress': 'Kannst du die Adresse senden?',

    // Coiffeur Dashboard
    'coiffeur.dashboard': 'Dashboard',
    'coiffeur.weeklyRevenue': 'Wochenumsatz',
    'coiffeur.weeklyAppt': 'Termine/Woche',
    'coiffeur.today': 'Heute',
    'coiffeur.rating': 'Bewertung',
    'coiffeur.activity': 'Aktivität',
    'coiffeur.estimatedNet': 'Umsatz (Netto geschätzt)',
    'coiffeur.total': 'Gesamt',
    'coiffeur.fees': 'Gebühren',
    'coiffeur.net': 'Netto',
    'coiffeur.proActions': 'Pro Aktionen',
    'coiffeur.flashBoost': 'Flash Boost',
    'coiffeur.manualAppt': 'Manueller Termin',
    'coiffeur.manualApptTitle': 'Neuer manueller Termin',
    'coiffeur.manualApptDesc': 'Termin außerhalb der App eintragen.',
    'coiffeur.clientName': 'Kundenname',
    'coiffeur.service': 'Leistung',
    'coiffeur.yourServices': 'IHRE LEISTUNGEN',
    'coiffeur.date': 'Datum',
    'coiffeur.time': 'Zeit',
    'coiffeur.saveAppt': 'Termin speichern',
    'coiffeur.flashBoostTitle': 'Flash Boost 🚀',
    'coiffeur.flashBoostDesc': '-15% für die nächsten 4 Stunden?',
    'coiffeur.later': 'Später',
    'coiffeur.activateBoost': 'Boost aktivieren',
    'coiffeur.boostActivated': 'Boost aktiv!',
    'coiffeur.boostActivatedDesc': 'Aktion ist live.',
    'coiffeur.clientMode': 'Kundenmodus',
    'coiffeur.bookService': 'Leistung buchen',
    'coiffeur.readyToLaunch': 'Bereit für den Salon?',
    'coiffeur.setupShowcase': 'Präsentieren Sie Ihren Salon.',
    'coiffeur.createSalon': 'Meinen Salon erstellen',
    'coiffeur.restrictedAccess': 'Eingeschränkter Zugriff',
    'coiffeur.init': 'Initialisierung...',
    'coiffeur.all': 'Alle',
    'coiffeur.pending': 'Ausstehend',
    'coiffeur.confirmed': 'Bestätigt',
    'coiffeur.blockDay': 'Tag sperren (Notfall)',
    'coiffeur.unblockDay': 'Tag entsperren',
    'coiffeur.noReservations': 'Keine Buchungen',
    'coiffeur.reservationsAppear': 'Buchungen erscheinen hier',
    'coiffeur.paymentMethod': 'Zahlungsart',
    'coiffeur.paidOnline': 'Online bezahlt',
    'coiffeur.remainingAtSalon': 'Rest im Salon',
    'coiffeur.confirm': 'Bestätigen',
    'coiffeur.cancel': 'Stornieren',
    'coiffeur.message': 'Nachricht',
    'coiffeur.validated': 'Termin validiert',
    'coiffeur.confirmTitle': 'Buchung bestätigen',
    'coiffeur.confirmDesc': 'Diese Buchung bestätigen?',
    'coiffeur.confirmSuccess': 'Buchung bestätigt.',
    'coiffeur.cancelTitle': 'Buchung absagen',
    'coiffeur.cancelWarning': 'Achtung: Antwort beeinflusst Image.',
    'coiffeur.cancelReasonLabel': 'Stornogrund:',
    'coiffeur.cancelReasonPlaceholder': 'Bsp: Notfall...',
    'coiffeur.keepAppt': 'Termin behalten',
    'coiffeur.confirmCancel': 'Storno bestätigen',
    'coiffeur.refundNote': '* Kunde wird automatisch erstattet.',
    'coiffeur.blockDayConfirm': 'Heute Buchungen schließen?',
    'coiffeur.unblockDayConfirm': 'Heute Buchungen öffnen?',
    'coiffeur.blockSuccess': 'Tag gesperrt.',
    'coiffeur.unblockSuccess': 'Buchungen wieder offen!',
    'coiffeur.cancelSuccess': 'Termin storniert.',
    'coiffeur.scheduleUpdated': 'Zeiten aktualisiert.',
    'coiffeur.scheduleUpdateError': 'Speichern fehlgeschlagen.',
    'coiffeur.confirmError': 'Bestätigen fehlgeschlagen.',
    'coiffeur.cancelError': 'Stornieren fehlgeschlagen.',
    'coiffeur.dayAlreadyBlocked': 'Tag bereits gesperrt.',
    'coiffeur.blockDayUrgency': 'Notfall: Tag sperren',
    'coiffeur.yesBlock': 'Ja, sperren',
    'coiffeur.yesUnblock': 'Ja, entsperren',
    'coiffeur.unblockDayTitle': 'Tag entsperren',
    'coiffeur.myStyles': 'Meine Stile',
    'coiffeur.catalog': 'Katalog',
    'coiffeur.myPrestations': 'Meine Leistungen',
    'coiffeur.loadingPrestations': 'Laden...',
    'coiffeur.catalogHint': 'Leistungen ankreuzen.',
    'coiffeur.alreadyConfigured': 'Konfiguriert',
    'coiffeur.addOtherPrestations': 'Weitere Leistungen',
    'coiffeur.noPrestation': 'Keine Leistung',
    'coiffeur.viewCatalog': 'Katalog ansehen',
    'coiffeur.removeStyle': 'Stil entfernen',
    'coiffeur.publishSalonNow': 'SALON VERÖFFENTLICHEN',
    'coiffeur.salonOnline': 'SALON ONLINE',
    'coiffeur.unpublish': 'Offline nehmen',
    'coiffeur.configStyles': 'Stile konfigurieren',
    'coiffeur.configStyle': 'Stil konfigurieren',
    'coiffeur.configTitle': 'Konfiguration',
    'coiffeur.priceEuro': 'Preis (€)',
    'coiffeur.durationMin': 'Dauer (Min)',
    'coiffeur.saveSuccess': 'Erfolgreich gespeichert.',
    'coiffeur.publishTitle': 'Salon veröffentlichen',
    'coiffeur.publishDesc': 'Sichtbar für alle.',
    'coiffeur.publishCongrat': 'Glückwunsch! 🎉',
    'coiffeur.publishCongratDesc': 'Salon ist online.',
    'coiffeur.managePrices': 'Preise verwalten',
    'coiffeur.rdvManagement': 'Terminverwaltung',
    'coiffeur.manageReservations': 'Buchungen einfach verwalten',
    'coiffeur.moreClients': 'Mehr Kunden',
    'coiffeur.increaseVisibility': 'Sichtbarkeit steigern',
    'coiffeur.statistics': 'Statistiken',
    'coiffeur.trackPerformance': 'Leistung verfolgen',
    'coiffeur.payments': 'Zahlungen',
    'coiffeur.securePayment': 'Sicher bezahlen lassen',
    'coiffeur.readyToStart': 'Bereit?',
    'coiffeur.createProAccount': 'Pro Konto erstellen',
    'coiffeur.needPhotoHelp': 'Foto Hilfe?',
    'coiffeur.photoHelpDesc': 'Gratis Hilfe kontaktieren!',

    // Favorites
    'fav.favorites': 'Favoriten',
    'fav.favoritesSubtitle': 'Deine Lieblingssalons und Stile',
    'fav.yourFavorites': 'Deine Favoriten',
    'fav.loginMessage': 'Anmelden für Favoriten.',
    'fav.salons': 'Salons',
    'fav.styles': 'Stile',
    'fav.noFavorites': 'Noch keine Favoriten',
    'fav.noStylesSaved': 'Noch keine Stile gespeichert',
    'fav.removeSuccess': 'Entfernt',

    // Profile
    'profile.settings': 'Einstellungen',
    'profile.language': 'Sprache',
    'profile.notifications': 'Benachrichtigungen',
    'profile.help': 'Hilfe',
    'profile.about': 'Über',
    'profile.rdv': 'Termine',
    'profile.salons': 'Salons',
    'profile.spent': 'Ausgegeben',
    'profile.modeCoiffeur': 'Friseurmodus',
    'profile.switchToCoiffeur': 'Friseurbereich',
    'profile.recentBookings': 'Letzte Termine',
    'profile.seeAll': 'Alle ansehen',
    'profile.noRecentBookings': 'Keine letzten Termine',
    'profile.messagesAlerts': 'Nachrichten & Alarme',
    'profile.myConversations': 'Meine Gespräche',
    'profile.myConversationsDesc': 'Chats mit Friseuren',
    'profile.notificationsDesc': 'Alarm Historie',
    'profile.account': 'Konto',
    'profile.editProfile': 'Profil bearbeiten',
    'profile.editProfileDesc': 'Name, Foto, Infos',
    'profile.settingsDesc': 'Sprache, Sicherheit',
    'profile.helpSupport': 'Hilfe & Support',
    'profile.logout': 'Abmelden',
    'profile.editProfileTitle': 'Mein Profil bearbeiten',
    'profile.fullName': 'Vollständiger Name',
    'profile.phone': 'Telefon',
    'profile.saveChanges': 'Speichern',
    'profile.appLanguage': 'App Sprache',
    'profile.preferences': 'Präferenzen',
    'profile.pushNotifications': 'Push Nachrichten',
    'profile.darkMode': 'Automatik Dunkelmodus',
    'profile.user': 'Benutzer',
    'profile.logoutConfirm': 'Abmelden?',

    // Hairstyles
    'hairstyle.tresses': 'Zöpfe',
    'hairstyle.locks': 'Locks',
    'hairstyle.coupe': 'Schnitt',
    'hairstyle.soins': 'Pflege',
    'hairstyle.coloration': 'Färbung',
    'hairstyle.tissage': 'Weave',
    'hairstyle.cornrows': 'Cornrows',
    'hairstyle.afro': 'Afro',

    // Salon Detail
    'salon.about': 'Über',
    'salon.services': 'Leistungen',
    'salon.reviews': 'Bewertungen',
    'salon.address': 'Adresse',
    'salon.bookNow': 'Jetzt buchen',
    'salon.openingHours': 'Öffnungszeiten',
    'salon.contact': 'Kontakt',
    'salon.noServices': 'Keine Leistungen.',
    'salon.noReviews': 'Keine Bewertungen.',
    'salon.verified': 'Verifiziert',
    'salon.call': 'Anrufen',
    'salon.share': 'Teilen',
    'salon.directions': 'Anfahrt',
    'salon.gallery': 'Galerie',
    'salon.stylists': 'Friseure',
    'salon.selectService': 'Wählen',
    'salon.selectedServices': 'gewählt',
    'salon.totalPrice': 'Gesamt',
    'salon.book': 'Weiter',

    // Salon Registration
    'salon.photos': 'Salon Fotos',
    'salon.addPhotos': 'Fotos hinzufügen',
    'salon.info': 'Salon Infos',
    'salon.name': 'Salon Name',
    'salon.description': 'Beschreibung',
    'salon.phone': 'Telefon',
    'salon.email': 'E-Mail',
    'salon.location': 'Standort',
    'salon.address': 'Adresse',
    'salon.city': 'Stadt',
    'salon.postalCode': 'PLZ',
    'salon.specialties': 'Spezialitäten',
    'salon.save': 'Speichern',
    'salon.saving': 'Speichere...',
    'salon.saved': 'Salon gespeichert!',
    'salon.homeService': 'Heimservice',
    'salon.homeServiceFee': 'Anfahrtsgebühr',
  },

  es: {
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.close': 'Cerrar',
    'common.next': 'Siguiente',
    'common.back': 'Atrás',
    'common.search': 'Buscar',
    'common.attention': 'Atención',
    'common.seeAll': 'Ver todo',
    'common.seeResults': 'Ver resultados',
    'common.results': 'resultados',
    'common.noResults': 'Sin resultados',
    'common.refresh': 'Actualizar',
    'common.refreshResults': 'Actualizando...',
    'common.distance': 'Distancia',
    'common.rating': 'Nota',
    'common.price': 'Precio',
    'common.errorOccurred': 'Ocurrió un error.',

    // Auth
    'auth.login': 'Iniciar sesión',
    'auth.register': 'Registrarse',
    'auth.logout': 'Cerrar sesión',
    'auth.email': 'Email',
    'auth.password': 'Contraseña',
    'auth.forgotPassword': '¿Olvidó su contraseña?',
    'auth.noAccount': '¿Sin cuenta?',
    'auth.hasAccount': '¿Ya tiene cuenta?',
    'auth.loginRequired': 'Identificación requerida',
    'auth.loginRequiredMessage': 'Por favor, inicie sesión.',

    // Home
    'home.welcome': 'Bienvenido a AfroPlan',
    'home.hello': 'Hola',
    'home.readyForHairstyle': '¿Disponible para un peinado?',
    'home.featured': 'Destacados',
    'home.hairstyleCategories': 'Categorías',
    'home.seeLess': 'Ver menos',
    'home.searchSalon': 'Buscar salón / peluquero',
    'home.searchSubtitle': 'Encuentra tu estilo',
    'home.promotions': 'Ofertas actuales',
    'home.hairstyles': 'Peinados',
    'home.nearbyCoiffeurs': 'Peluqueros cercanos',
    'home.popularSalons': 'Salones populares',
    'home.tipsAndInspiration': 'Consejos e Inspiración',
    'home.areYouCoiffeur': '¿Eres peluquero?',
    'home.joinAfroPlanPro': 'Crece con AfroPlan Pro',
    'home.discoverPro': 'Descubrir AfroPlan Pro',

    // Onboarding
    'onboarding.slide1Title': 'Revela tu estilo',
    'onboarding.slide1Subtitle': 'Descubre los mejores peluqueros afro de tu zona.',
    'onboarding.slide2Title': 'Reserva fácil',
    'onboarding.slide2Subtitle': 'Reserva una cita en pocos clics, en cualquier momento.',
    'onboarding.slide3Title': 'Experticia certificada',
    'onboarding.slide3Subtitle': 'Profesionales apasionados para cuidar de ti.',
    'onboarding.touchToContinue': 'Toca la pantalla para continuar',

    // Search Flow
    'search.findCoiffeur': 'Encuentra tu peluquero afro',
    'search.quickQuestions': 'Preguntas rápidas para mejores salones.',
    'search.chooseStyle': 'Elige tu peinado',
    'search.chooseCategory': 'Elige tu categoría',
    'search.whatTypeHairstyle': '¿Qué tipo de peinado?',
    'search.step': 'Paso',
    'search.of': 'de',
    'search.backAtAnyTime': 'Puedes volver atrás',
    'search.locationTemporarilyDisabled': 'Localización desactivada',
    'search.whatStyle': '¿Qué estilo te gustaría?',
    'search.quickFilter': 'Filtro rápido',
    'search.hairType': 'Tipo de cabello',
    'search.whereCoiffeur': '¿Dónde peinarse?',
    'search.inSalon': 'En el salón',
    'search.atHome': 'A domicilio',
    'search.budgetDistance': 'Presupuesto y Distancia',
    'search.maxBudget': 'Presupuesto máx',
    'search.maxDistance': 'Distancia máx',
    'search.showAllSalons': 'Ver todos los salones',
    'search.paymentInfo': 'Elija pago total o anticipo.',
    'search.quickPay': 'Pago rápido',

    // Booking
    'booking.myReservations': 'Mis reservas',
    'booking.book': 'Reservar',
    'booking.confirmed': 'Confirmado',
    'booking.pending': 'Pendiente',
    'booking.cancelled': 'Cancelado',
    'booking.completed': 'Completado',
    'booking.loginMessage': 'Inicie sesión para ver reservas',
    'booking.noUpcoming': 'Sin citas próximas',
    'booking.noPast': 'Sin citas pasadas',
    'booking.exploreSalons': 'Explorar salones',
    'booking.cancelImpossible': 'Cancelación imposible',
    'booking.cancelAndRefund': '¿Cancelar y reembolsar?',
    'booking.amountPaid': 'Pagado',
    'booking.cancelFee': 'Gasto de cancelación',
    'booking.amountRefunded': 'Reembolsado',
    'booking.keepAppt': 'Mantener cita',
    'booking.confirmCancel': 'Confirmar cancelación',
    'booking.cancelSuccess': 'Cita cancelada.',
    'booking.cancelRefundProcessing': 'Reembolso en curso.',
    'booking.cancelAppt': 'Cancelar cita',
    'booking.cancelConfirmMessage': '¿Seguro que desea cancelar?',
    'booking.cancelFinalSuccess': 'Cita eliminada.',
    'booking.deleteError': 'No se pudo eliminar.',
    'booking.noEdit': 'No editable.',
    'booking.cancelReason': 'Motivo',
    'booking.unavailable': 'No disponible',
    'booking.upcoming': 'Próximas',
    'booking.past': 'Pasadas',
    'booking.yes': 'Sí',
    'booking.no': 'No',
    'booking.yesCancel': 'Sí, cancelar',
    'booking.wantToContinue': '¿Desea continuar?',

    // Chat
    'chat.writeMessage': 'Escribir mensaje...',
    'chat.online': 'En línea',
    'chat.reservationConfirmed': '¡Reserva confirmada! Chatear.',
    'chat.willBeLate': 'Llegaré un poco tarde',
    'chat.onMyWay': 'Estoy en camino',
    'chat.whatTime': '¿A qué hora exactamente?',
    'chat.sendAddress': '¿Puedes enviar la dirección?',

    // Coiffeur Dashboard
    'coiffeur.dashboard': 'Panel de control',
    'coiffeur.weeklyRevenue': 'Ingresos semanales',
    'coiffeur.weeklyAppt': 'Citas/sem',
    'coiffeur.today': 'Hoy',
    'coiffeur.rating': 'Nota',
    'coiffeur.activity': 'Actividad',
    'coiffeur.estimatedNet': 'Ingresos (Neto est.)',
    'coiffeur.total': 'Total',
    'coiffeur.fees': 'Comisiones',
    'coiffeur.net': 'Neto',
    'coiffeur.proActions': 'Acciones Pro',
    'coiffeur.flashBoost': 'Boost Flash',
    'coiffeur.manualAppt': 'Cita Manual',
    'coiffeur.manualApptTitle': 'Nueva Cita Manual',
    'coiffeur.manualApptDesc': 'Registrar cita fuera de la app.',
    'coiffeur.clientName': 'Nombre del cliente',
    'coiffeur.service': 'Servicio',
    'coiffeur.yourServices': 'SUS SERVICIOS',
    'coiffeur.date': 'Fecha',
    'coiffeur.time': 'Hora',
    'coiffeur.saveAppt': 'Guardar cita',
    'coiffeur.flashBoostTitle': 'Boost Flash 🚀',
    'coiffeur.flashBoostDesc': '¿Activar -15% por 4 horas?',
    'coiffeur.later': 'Más tarde',
    'coiffeur.activateBoost': 'Activar Boost',
    'coiffeur.boostActivated': '¡Boost activo!',
    'coiffeur.boostActivatedDesc': 'Promoción activa.',
    'coiffeur.clientMode': 'Modo Cliente',
    'coiffeur.bookService': 'Reservar servicio',
    'coiffeur.readyToLaunch': '¿Listo para lanzar?',
    'coiffeur.setupShowcase': 'Configure su salón.',
    'coiffeur.createSalon': 'Crear mi salón',
    'coiffeur.restrictedAccess': 'Acceso restringido',
    'coiffeur.init': 'Iniciando...',
    'coiffeur.all': 'Todas',
    'coiffeur.pending': 'Pendiente',
    'coiffeur.confirmed': 'Confirmadas',
    'coiffeur.blockDay': 'Bloquear día (Urgencia)',
    'coiffeur.unblockDay': 'Desbloquear día',
    'coiffeur.noReservations': 'Sin reservas',
    'coiffeur.reservationsAppear': 'Las reservas aparecerán aquí',
    'coiffeur.paymentMethod': 'Método de pago',
    'coiffeur.paidOnline': 'Pagado online',
    'coiffeur.remainingAtSalon': 'Resto en salón',
    'coiffeur.confirm': 'Confirmar',
    'coiffeur.cancel': 'Cancelar',
    'coiffeur.message': 'Mensaje',
    'coiffeur.validated': 'Cita validada',
    'coiffeur.confirmTitle': 'Confirmar reserva',
    'coiffeur.confirmDesc': '¿Confirmar esta reserva?',
    'coiffeur.confirmSuccess': 'Reserva confirmada.',
    'coiffeur.cancelTitle': 'Cancelar cita',
    'coiffeur.cancelWarning': 'Ojo: Su respuesta afecta su imagen.',
    'coiffeur.cancelReasonLabel': 'Motivo:',
    'coiffeur.cancelReasonPlaceholder': 'Ej: Urgencia...',
    'coiffeur.keepAppt': 'Mantener cita',
    'coiffeur.confirmCancel': 'Confirmar cancelación',
    'coiffeur.refundNote': '* El cliente será reembolsado.',
    'coiffeur.blockDayConfirm': '¿Cerrar reservas para hoy?',
    'coiffeur.unblockDayConfirm': '¿Abrir reservas para hoy?',
    'coiffeur.blockSuccess': 'Día bloqueado.',
    'coiffeur.unblockSuccess': '¡Reservas abiertas!',
    'coiffeur.cancelSuccess': 'Cita cancelada.',
    'coiffeur.scheduleUpdated': 'Horarios actualizados.',
    'coiffeur.scheduleUpdateError': 'Error al guardar.',
    'coiffeur.confirmError': 'No se pudo confirmar.',
    'coiffeur.cancelError': 'No se pudo cancelar.',
    'coiffeur.dayAlreadyBlocked': 'Día ya bloqueado.',
    'coiffeur.blockDayUrgency': 'Urgencia: Bloquear día',
    'coiffeur.yesBlock': 'Sí, bloquear',
    'coiffeur.yesUnblock': 'Sí, desbloquear',
    'coiffeur.unblockDayTitle': 'Desbloquear día',
    'coiffeur.myStyles': 'Mis estilos',
    'coiffeur.catalog': 'Catálogo',
    'coiffeur.myPrestations': 'Mis servicios',
    'coiffeur.loadingPrestations': 'Cargando...',
    'coiffeur.catalogHint': 'Marque los estilos.',
    'coiffeur.alreadyConfigured': 'Configurado',
    'coiffeur.addOtherPrestations': 'Más servicios',
    'coiffeur.noPrestation': 'Sin servicios',
    'coiffeur.viewCatalog': 'Ver catálogo',
    'coiffeur.removeStyle': 'Quitar estilo',
    'coiffeur.publishSalonNow': 'PUBLICAR MI SALÓN',
    'coiffeur.salonOnline': 'SALÓN ONLINE',
    'coiffeur.unpublish': 'Despublicar',
    'coiffeur.configStyles': 'Configurar estilos',
    'coiffeur.configStyle': 'Configurar estilo',
    'coiffeur.configTitle': 'Configuración',
    'coiffeur.priceEuro': 'Precio (€)',
    'coiffeur.durationMin': 'Duración (min)',
    'coiffeur.saveSuccess': 'Guardado con éxito.',
    'coiffeur.publishTitle': 'Publicar salón',
    'coiffeur.publishDesc': 'Visible para todos.',
    'coiffeur.publishCongrat': '¡Felicidades! 🎉',
    'coiffeur.publishCongratDesc': 'Salón en línea.',
    'coiffeur.managePrices': 'Gestionar precios',
    'coiffeur.rdvManagement': 'Gestión de Citas',
    'coiffeur.manageReservations': 'Gestione reservas fácilmente',
    'coiffeur.moreClients': 'Más clientes',
    'coiffeur.increaseVisibility': 'Aumente su visibilidad',
    'coiffeur.statistics': 'Estadísticas',
    'coiffeur.trackPerformance': 'Siga su rendimiento',
    'coiffeur.payments': 'Pagos',
    'coiffeur.securePayment': 'Cobre con seguridad',
    'coiffeur.readyToStart': '¿Listo?',
    'coiffeur.createProAccount': 'Crear cuenta Pro',
    'coiffeur.needPhotoHelp': '¿Ayuda con fotos?',
    'coiffeur.photoHelpDesc': '¡Ayuda gratis disponible!',

    // Favorites
    'fav.favorites': 'Favoritos',
    'fav.favoritesSubtitle': 'Tus salones y estilos preferidos',
    'fav.yourFavorites': 'Tus favoritos',
    'fav.loginMessage': 'Inicia sesión para favoritos.',
    'fav.salons': 'Salones',
    'fav.styles': 'Estilos',
    'fav.noFavorites': 'Sin favoritos aún',
    'fav.noStylesSaved': 'Sin estilos guardados',
    'fav.removeSuccess': 'Quitado',

    // Profile
    'profile.settings': 'Ajustes',
    'profile.language': 'Idioma',
    'profile.notifications': 'Notificaciones',
    'profile.help': 'Ayuda',
    'profile.about': 'Acerca de',
    'profile.rdv': 'Citas',
    'profile.salons': 'Salones',
    'profile.spent': 'Gastado',
    'profile.modeCoiffeur': 'Modo Peluquero',
    'profile.switchToCoiffeur': 'Área peluquero',
    'profile.recentBookings': 'Citas recientes',
    'profile.seeAll': 'Ver todo',
    'profile.noRecentBookings': 'Sin citas recientes',
    'profile.messagesAlerts': 'Mensajes y Alertas',
    'profile.myConversations': 'Mis conversaciones',
    'profile.myConversationsDesc': 'Chats con peluqueros',
    'profile.notificationsDesc': 'Historial de alertas',
    'profile.account': 'Cuenta',
    'profile.editProfile': 'Editar perfil',
    'profile.editProfileDesc': 'Nombre, foto, info',
    'profile.settingsDesc': 'Idioma, seguridad',
    'profile.helpSupport': 'Ayuda y Soporte',
    'profile.logout': 'Cerrar sesión',
    'profile.editProfileTitle': 'Editar mi perfil',
    'profile.fullName': 'Nombre completo',
    'profile.phone': 'Teléfono',
    'profile.saveChanges': 'Guardar',
    'profile.appLanguage': 'Idioma de la app',
    'profile.preferences': 'Preferencias',
    'profile.pushNotifications': 'Notificaciones Push',
    'profile.darkMode': 'Modo oscuro auto',
    'profile.user': 'Usuario',
    'profile.logoutConfirm': '¿Cerrar sesión?',

    // Hairstyles
    'hairstyle.tresses': 'Trenzas',
    'hairstyle.locks': 'Locks',
    'hairstyle.coupe': 'Corte',
    'hairstyle.soins': 'Tratamientos',
    'hairstyle.coloration': 'Coloración',
    'hairstyle.tissage': 'Tejido',
    'hairstyle.cornrows': 'Cornrows',
    'hairstyle.afro': 'Afro',

    // Salon Detail
    'salon.about': 'Acerca de',
    'salon.services': 'Servicios',
    'salon.reviews': 'Opiniones',
    'salon.address': 'Dirección',
    'salon.bookNow': 'Reservar ya',
    'salon.openingHours': 'Horarios',
    'salon.contact': 'Contacto',
    'salon.noServices': 'Sin servicios.',
    'salon.noReviews': 'Sin opiniones.',
    'salon.verified': 'Verificado',
    'salon.call': 'Llamar',
    'salon.share': 'Compartir',
    'salon.directions': 'Cómo llegar',
    'salon.gallery': 'Galería',
    'salon.stylists': 'Peluqueros',
    'salon.selectService': 'Seleccionar',
    'salon.selectedServices': 'elegidos',
    'salon.totalPrice': 'Total',
    'salon.book': 'Continuar',

    // Salon Registration
    'salon.photos': 'Fotos del salón',
    'salon.addPhotos': 'Añadir fotos',
    'salon.info': 'Info del salón',
    'salon.name': 'Nombre del salón',
    'salon.description': 'Descripción',
    'salon.phone': 'Teléfono',
    'salon.email': 'Email',
    'salon.location': 'Ubicación',
    'salon.address': 'Dirección',
    'salon.city': 'Ciudad',
    'salon.postalCode': 'Código postal',
    'salon.specialties': 'Especialidades',
    'salon.save': 'Guardar',
    'salon.saving': 'Guardando...',
    'salon.saved': '¡Salón guardado!',
    'salon.homeService': 'Servicio a domicilio',
    'salon.homeServiceFee': 'Tasa de viaje',
  },
};

const LANGUAGE_STORAGE_KEY = '@afroplan_language';

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('fr');

  // Load saved language on mount
  useEffect(() => {
    loadSavedLanguage();
  }, []);

  const loadSavedLanguage = async () => {
    try {
      const savedLanguage = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY);
      if (savedLanguage && ['fr', 'en', 'de', 'es'].includes(savedLanguage)) {
        setLanguageState(savedLanguage as Language);
      }
    } catch (error) {
      console.error('Error loading language:', error);
    }
  };

  const setLanguage = async (lang: Language) => {
    try {
      await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
      setLanguageState(lang);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  };

  // Translation function
  const t = (key: string): string => {
    // 1. Chercher dans la langue actuelle
    if (translations[language] && translations[language][key]) {
      return translations[language][key];
    }
    // 2. Secours : Chercher en français
    if (translations['fr'] && translations['fr'][key]) {
      return translations['fr'][key];
    }
    // 3. Dernier recours : Nettoyer la clé pour qu'elle soit lisible
    // ex: 'onboarding.slide1Title' -> 'Slide1Title'
    return key.split('.').pop() || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        languages: LANGUAGES,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
